version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: ["/app/docker/wait_for_it.sh", "db", "5432", "/app/docker/run_migrations.sh"]
    env_file:
      - .env
    ports:
      - "9999:8000"
    depends_on:
      - db
    restart: always