"""init2

Revision ID: 86f99705547e
Revises: 18ecb9368fbe
Create Date: 2023-09-14 08:19:29.249289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86f99705547e"
down_revision: Union[str, None] = "18ecb9368fbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "task", ["id"])
    op.drop_constraint("user_hashed_password_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_hashed_password_key", "user", ["hashed_password"])
    op.drop_constraint(None, "task", type_="unique")
    # ### end Alembic commands ###
